[profile.default]
src = "contracts/src"
out = "out"
libs = ["lib"]

remappings = [
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/",
  "forge-std/=lib/forge-std/src/"
]

optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"